#NCD publication Parameters 
#Please check the confluence page for the standardised values

[Setup]
test_mode = "false"    #Must be lower case - "true" = test mode, "false" = live run

[Dates]
Publication_date = "MMM_YYYY"    #MMM_YYYY

[Filepaths]
root_directory  = "insert path to your root directory here"


[Connections]
server          = "server name"
database        = "database name"


[Indicators]
removal_indicator_list = []

[Measures]
bad_measure_list =  []

[Pairs]


